module: SequenceModule
model:
  model_name: deepbind_st
  arch_name: DeepBind
  arch:
    input_len: 41
    output_dim: 1
    conv_kwargs:
      input_channels: 4
      conv_channels: [16]
      conv_kernels: [16]
      dropout_rates: [0.1]
      batchnorm: true
    dense_kwargs:
      hidden_dims: [32]
      dropout_rates: [0.5]
      batchnorm: true
  task: regression
  loss_fxn: mse
  optimizer: adam
  optimizer_lr: 0.005
  scheduler_kwargs:
    patience: 2
