module: SequenceModule
model:
  model_name: Jores21CNN
  arch_name: Jores21CNN
  arch:
    input_len: 170
    output_dim: 1
    layers: 3
    filters: 256
    kernel_size: 13
    stride: 1
    hidden_dim: 64
    dropout: 0.3
  task: "regression"
  loss_fxn: "mse"
task: regression
loss_fxn: mse
optimizer: adam
optimizer_lr: 0.001
scheduler: reduce_lr_on_plateau
scheduler_monitor: val_loss_epoch
scheduler_kwargs:
  patience: 2
  