arch:
  input_len: 500
  output_dim: 1
  aggr: concat_cnn
  conv_kwargs:
    input_channels: 4
    conv_channels: [10, 8]
    conv_kernels: [11, 3]
    conv_strides: [1, 1]
    pool_types: [max, null]
    pool_kernels: [30, null]
    pool_strides: [1, null]
    dropout_rates: 0.2
    batchnorm: True
    activations: relu
  recurrent_kwargs:
    hidden_dim: 128
    batch_first: True
  dense_kwargs:
    hidden_dims: [64]
    dropout_rates: 0.2
    batchnorm: True
