model:  
  input_len: 500
  output_dim: 1
  aggr: max
  strand: ds
  task: binary_classification
  loss_fxn: bce
  conv_kernel_size: [11, 3]
  filters: [10, 8]
  maxpool_kernel_size: 30
  stride: 1
  lr: 0.001
  optimizer: adam
  optimizer_kwargs:
    amsgrad: true
  scheduler: lr_scheduler
  scheduler_patience: 2

  
